### ISSUE TITLE
Disabling reactive in juju_info

### ISSUE THREAD

**Issue by ktsakalozos** [boucherv/charm-keepalived#1]
What is the purpose of effectively disabling reactive in the juju_info departed and broken relations?
https://github.com/boucherv/charm-keepalived/commit/bf98e2a5e1f0c2cc9fb93b30a70877804fa99baf

**Comment by boucherv** [comment]
These two relation hook failed if we call reactive .. There are no impact on the keepalived service because no state use these two hooks .. I know this is not the best way to fix the issue ! I can spend more time to find the source of the issue! 

The current charm is really robust, we deploy it with Kubernetes many times and it's works!

**Comment by ktsakalozos** [comment]
Would it be possible to show me the error you get? I am afraid we will not be able to merge this upstream.

**Comment by ktsakalozos** [comment]
This should be addressed with the recent refactoring.
